### ISSUE TITLE
Carousel Maps

### ISSUE THREAD

**Issue by anmaro13** [anmaro13/anmaro13.github.io#2]
No consigo que me salga el carousel de mapas que te comenté, si le puedes  echar un ojo al código y me dices algún consejito te lo agradecería. El problema lo tengo en la carpeta Curriculum2.
Gracias!
@hhkaos

**Comment by hhkaos** [comment]
Ok, lo intento ver antes del lunes ;)

**Comment by anmaro13** [comment]
Hola Raul,
Es una pregunta rápida, me molaría hacerme un avatar y colocarlo en los
distintos perfiles que tengo en vez de una foto mía. ¿Alguna recomendación
de donde hacerme el avatar personalizado?.

Gracias!

2017-02-17 8:20 GMT+01:00 Raul Jimenez Ortega <notifications@github.com>:

**Comment by aicelm** [comment]
Hola!
He visto un montón de páginas buscando para hacer avatares, son bastante sencillos, mira a ver si te molan, 

Te copio: 

- http://www.faceyourmanga.com/editmangatar.php
- https://hipertextual.com/2017/02/crear-tu-propio-avatar-personalizado

;)

**Comment by anmaro13** [comment]
Gracias Leti! les echo un ojo ;)

**Comment by hhkaos** [comment]
Andrea a qué carousel te refieres? a mi este me funciona:
![2017-02-22 16_09_05](https://cloud.githubusercontent.com/assets/826965/23217368/46ae9822-f919-11e6-93f2-487a36e1aed3.gif)

**Comment by hhkaos** [comment]
Acaba de llegarte un "pull request" mío. [Ahí puedes ver el problema](https://github.com/hhkaos/anmaro13.github.io/commit/beb5bb1f64899d3ef84c2352bf385f78120d72d9), el tema es que en el código JavaScript sólo le estabas dando el comportamiento al elemento HTML con id "#testimonial-carousel", yo te he añadido el ```, #works-carousel``` para que también le añada el comportamiento de carousel al elemento de la pestaña "works" ;). Lo he probado en mi PC y ha funcionado ;).

Por cierto, cuando hagas los "commits" añade un mensaje que tenga sentido!, que [como lo estás haciendo](https://github.com/anmaro13/anmaro13.github.io/commits/master) es imposible hacer un seguimiento de qué estás cambiando en cada versión ;P

Un abrazo!
